Add example for filtering across associations
rcdilorenzo/filtrex pull request #56
Opened 2018-10-29 21:28 UTC by chevinbrown

This is a _very_ basic example of how to filter across associations. It works for me, but there may be a more clear way to do this, especially with Ecto 3 hot off the press. 😄 

@rcdilorenzo sorry this promise took so long!

2018-10-31 20:07 UTC, rcdilorenzo requested changes
Thanks so much @chevinbrown. I've suggested a couple of super minor changes, but otherwise looks good. If you make the changes, I'll try and merge it tonight in case you're pursuing Octoberfest. 😄

2018-10-31 20:07 UTC, rcdilorenzo commented on README.md
> +    query =
Let's add a separation comment here to remain consistent.
```suggestion
    # step 3: combine queries
    query =
```

2018-10-31 20:07 UTC, rcdilorenzo commented on README.md
> +## Filtering across associations
Adjust capitalization for consistency
```suggestion
## Filtering Across Associations
```

2018-11-02 00:34 UTC, chevinbrown commented
@rcdilorenzo looks good to me! 💸

2018-11-03 15:56 UTC, merged